/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadlastweek;

import interfacethings.DLWOptionPane;
import interfacethings.ImageFond;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Aula1
 */
public class Game extends javax.swing.JFrame {
    Decision historia = new Historia().getHistory();
    Historia h = new Historia();
    boolean isfinal = false;
    boolean isthereagamesaved = false;
    SimpleAttributeSet attribs = new SimpleAttributeSet();
    DLWOptionPane dialog;
    private Cursor cursor;

    int s = 30;

    /**
     * Creates new form Game
     * @param isThereAGameSaved
     */
    public Game(boolean isThereAGameSaved) {
        initComponents();        
        anotherInitComponents(isThereAGameSaved);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageFond image = new ImageFond();
        image.setImage("/images/Fondo.jpg");
        setContentPane(image);
        fondo = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        days = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jScrollPaneFond = new javax.swing.JScrollPane();
        textfond = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titlepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pjbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        buttonspanel = new javax.swing.JPanel();
        twooptionspanel = new javax.swing.JPanel();
        optionabutton = new javax.swing.JButton();
        clockpanel = new javax.swing.JPanel();
        clockicon = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        optionbbutton = new javax.swing.JButton();
        continueoptionpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        continuebutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Dad's Last Week");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        fondo.setOpaque(false);
        fondo.setLayout(new java.awt.BorderLayout());

        contenido.setOpaque(false);
        contenido.setLayout(new javax.swing.BoxLayout(contenido, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("                  ");
        contenido.add(jLabel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setText(" ");
        jPanel4.add(jLabel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        days.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        days.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        days.setText("Prólogo");
        days.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(days);

        jPanel4.add(jPanel5);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel5.setText(" ");
        jPanel4.add(jLabel5);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new javax.swing.OverlayLayout(jPanel6));

        jScrollPane.setBorder(null);
        jScrollPane.setOpaque(false);

        text.setEditable(false);
        text.setBorder(null);
        text.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        text.setOpaque(false);
        jScrollPane.setViewportView(text);

        jPanel6.add(jScrollPane);

        jScrollPaneFond.setBorder(null);
        jScrollPaneFond.setEnabled(false);
        jScrollPaneFond.setOpaque(false);

        textfond.setEditable(false);
        textfond.setColumns(20);
        textfond.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        textfond.setRows(5);
        textfond.setFocusable(false);
        textfond.setOpaque(false);
        jScrollPaneFond.setViewportView(textfond);

        jPanel6.add(jScrollPaneFond);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        contenido.add(jPanel3);

        jLabel3.setText("                  ");
        contenido.add(jLabel3);
        contenido.add(jSeparator1);

        fondo.add(contenido, java.awt.BorderLayout.CENTER);

        titlepanel.setOpaque(false);
        titlepanel.setLayout(new javax.swing.OverlayLayout(titlepanel));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("                                                                                                                       ");
        jPanel2.add(jLabel1);

        pjbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        pjbutton.setContentAreaFilled(false);
        pjbutton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pjbutton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pjbutton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pjbutton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pjbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pjbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pjbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pjbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pjbuttonMouseReleased(evt);
            }
        });
        pjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(pjbutton);

        titlepanel.add(jPanel2);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titulo);

        titlepanel.add(jPanel1);

        fondo.add(titlepanel, java.awt.BorderLayout.PAGE_START);

        buttonspanel.setOpaque(false);
        buttonspanel.setLayout(new javax.swing.OverlayLayout(buttonspanel));

        twooptionspanel.setOpaque(false);
        twooptionspanel.setLayout(new java.awt.GridLayout(1, 0));

        optionabutton.setBorderPainted(false);
        optionabutton.setContentAreaFilled(false);
        optionabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionabuttonActionPerformed(evt);
            }
        });
        twooptionspanel.add(optionabutton);

        clockpanel.setOpaque(false);
        clockpanel.setLayout(new java.awt.GridLayout(2, 1));

        clockicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockpanel.add(clockicon);

        time.setFont(new java.awt.Font("Old English Text MT", 1, 20)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockpanel.add(time);

        twooptionspanel.add(clockpanel);

        optionbbutton.setBorderPainted(false);
        optionbbutton.setContentAreaFilled(false);
        optionbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionbbuttonActionPerformed(evt);
            }
        });
        twooptionspanel.add(optionbbutton);

        buttonspanel.add(twooptionspanel);

        continueoptionpanel.setOpaque(false);
        continueoptionpanel.setLayout(new java.awt.GridLayout(1, 0));
        continueoptionpanel.add(jLabel7);

        continuebutton.setBorderPainted(false);
        continuebutton.setContentAreaFilled(false);
        continuebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuebuttonActionPerformed(evt);
            }
        });
        continueoptionpanel.add(continuebutton);
        continueoptionpanel.add(jLabel6);

        buttonspanel.add(continueoptionpanel);

        fondo.add(buttonspanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anotherInitComponents(boolean isThereAGameSaved){
        isthereagamesaved = isThereAGameSaved;
        //CURSOR
        ImageIcon imagencursor = new ImageIcon(getClass().getResource("/images/cursor.png"));
        Toolkit TK = Toolkit.getDefaultToolkit(); 
        this.cursor = TK.createCustomCursor(imagencursor.getImage(), new Point(2,2),"Cursor 01"); 
        this.setCursor(cursor);
        
        new DadsLastWeek().setIsPlaying(true);
        
        jScrollPaneFond.getViewport().setOpaque(false);
        jScrollPaneFond.setViewportBorder(null);
        textfond.setBackground(new Color(0, 0, 0, 0));
        
        jScrollPane.getViewport().setOpaque(false);
        jScrollPane.setViewportBorder(null);
        Color bgColor = new Color(0, 0, 0, 0);
        SimpleAttributeSet style = new SimpleAttributeSet();
        StyleConstants.setBackground(style, bgColor);
        StyleConstants.setAlignment(style, StyleConstants.ALIGN_JUSTIFIED);
        text.getStyledDocument().setParagraphAttributes(0, text.getDocument().getLength(), style, false);
        text.setBackground(bgColor);
        text.setParagraphAttributes(style, false);

        Image mini = new ImageIcon(getClass().getResource("/images/Titulo.png")).getImage().getScaledInstance(200, 95, Image.SCALE_AREA_AVERAGING);
        titulo.setIcon(new ImageIcon(mini));        
        this.setSize(500,600);
        Image ico = new ImageIcon(getClass().getResource("/images/calendar_5-512.png")).getImage().getScaledInstance(2000, 1900, Image.SCALE_AREA_AVERAGING);
        this.setIconImage(ico);
        Image personajeboton;

        ImageIcon reloj = new ImageIcon(getClass().getResource("/images/clock.gif"));
        try{
            personajeboton = new Database().consultarImagen(new DadsLastWeek().getIdusuario()).getImage().getScaledInstance(25, 25, java.awt.Image.SCALE_AREA_AVERAGING);
        }catch(NullPointerException ex){
            personajeboton = new ImageIcon(getClass().getResource("/images/withoutphoto.png")).getImage().getScaledInstance(25,25, Image.SCALE_AREA_AVERAGING);
        }
        pjbutton.setIcon(new ImageIcon(personajeboton));
        clockicon.setIcon(reloj);
        reloj.setImageObserver(clockicon);
        if(isThereAGameSaved){
            recoverData();
        }else{
            text.setText(historia.event);
            twooptionspanel.setVisible(false);
        }
        continuebutton.setIcon(new ImageIcon(continuarboton1));
        continuebutton.setRolloverIcon(new ImageIcon(continuarboton2));
        continuebutton.setPressedIcon(new ImageIcon(continuarboton3));
    }
    
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            time.setText(String.valueOf(s));
            if (s == 0) {
                Random aleatorio = new Random();
                int opcion = aleatorio.nextInt(2);
                if(opcion == 0){
                    historia = historia.left;
                    new DadsLastWeek().setDia_coddia(historia.day);
                    new DadsLastWeek().setDecision_iddecision(historia.decision);
                }else{
                    historia = historia.right;
                    new DadsLastWeek().setDia_coddia(historia.day);
                    new DadsLastWeek().setDecision_iddecision(historia.decision);
                }
                s = 30;
                timer.stop();
                initHistory();
            }else if(!new DadsLastWeek().isIsPjWindowOpened()){
                s--;
            }
        }
    });
    
    private void initHistory(){
        days.setText(h.obtenerDia(historia.day));
        text.setText(historia.event);
        new DadsLastWeek().setSalud(historia.health);
        new DadsLastWeek().setEstadosalud(historia.healthstate);
        if("D002".equals(new DadsLastWeek().getDia_coddia()) || "D003".equals(new DadsLastWeek().getDia_coddia()) || "D004".equals(new DadsLastWeek().getDia_coddia()) || "D005".equals(new DadsLastWeek().getDia_coddia()) || "D006".equals(new DadsLastWeek().getDia_coddia())|| "D007".equals(new DadsLastWeek().getDia_coddia())){
            new Database().actualizarDiaYDecision(new DadsLastWeek().getIdusuario(), new DadsLastWeek().getDia_coddia(), new DadsLastWeek().getDecision_iddecision());
            new Database().actualizarPersonaje(new DadsLastWeek().getIdusuario(), new DadsLastWeek().getNompersonaje(), new DadsLastWeek().getApellpersonaje(), new DadsLastWeek().getSalud(), new DadsLastWeek().getEstadosalud());
        }
        if(historia.right != null && historia.left != null){
            timer.start();
            continueoptionpanel.setVisible(false);
            twooptionspanel.setVisible(true);
            optionabutton.setIcon(new ImageIcon(historia.left.button1));
            optionabutton.setRolloverIcon(new ImageIcon(historia.left.button2));
            optionabutton.setPressedIcon(new ImageIcon(historia.left.button3));
            optionbbutton.setIcon(new ImageIcon(historia.right.button1));
            optionbbutton.setRolloverIcon(new ImageIcon(historia.right.button2));
            optionbbutton.setPressedIcon(new ImageIcon(historia.right.button3));
            directions();
//            s = 30;
        }else if(historia.right == null && historia.left != null){
            timer.stop();
            twooptionspanel.setVisible(false);
            continueoptionpanel.setVisible(true);
            directions();
        }else if(historia.right == null && historia.left == null){
            timer.stop();
            isfinal = true;
            continuebutton.setIcon(new ImageIcon(finalboton1));
            continuebutton.setRolloverIcon(new ImageIcon(finalboton2));
            continuebutton.setPressedIcon(new ImageIcon(finalboton3));
            directions();
        }
    }
    
    private void directions() {
        if(historia.object != null){
            ArrayList<ArrayList<String>> objactuales = new DadsLastWeek().getListaobjetos();
            int howmanywithminus = 0;

            String[] variosobjetos = historia.object.split(",");
            for (String variosobjeto : variosobjetos) {
                if (variosobjeto.contains("-")) {
                    howmanywithminus++;
                }
            }
            String[] addobjetos = new String[variosobjetos.length - howmanywithminus];
            String[] removeobjetos = new String[howmanywithminus];
            
            if(!isthereagamesaved){
                boolean horadeguardar = false;
                if("D001".equals(new DadsLastWeek().getDia_coddia()) || "D002".equals(new DadsLastWeek().getDia_coddia()) || "D003".equals(new DadsLastWeek().getDia_coddia()) || "D004".equals(new DadsLastWeek().getDia_coddia()) || "D005".equals(new DadsLastWeek().getDia_coddia()) || "D006".equals(new DadsLastWeek().getDia_coddia())){
                    horadeguardar = true;
                }

                
                for (int i = 0; i < removeobjetos.length; i++) {
                    for (int j = i; j < variosobjetos.length; j++) {
                        if (variosobjetos[j].contains("-")) {
                            removeobjetos[i] = variosobjetos[j].replace("-", "");
                            j = variosobjetos.length;
                            if(horadeguardar || "D007".equals(new DadsLastWeek().getDia_coddia())){
                                new Database().insertarOBorrarObjetos(new DadsLastWeek().getIdusuario(), removeobjetos[i], false);
                            }
                        }
                    }
                }

                for (int i = 0; i < addobjetos.length; i++) {
                    for (int j = i; j < variosobjetos.length; j++) {
                        if (!variosobjetos[j].contains("-")) {
                            addobjetos[i] = variosobjetos[j];
                            j = variosobjetos.length;
                            if(horadeguardar || "D007".equals(new DadsLastWeek().getDia_coddia())){
                                new Database().insertarOBorrarObjetos(new DadsLastWeek().getIdusuario(), addobjetos[i], true);
                            }
                        }
                    }
                }
            }

            if (!objactuales.isEmpty()) {
                for (String addobjeto : addobjetos) {
                    objactuales.get(0).add(addobjeto);
                    objactuales.get(1).add(new Database().buscaNomObjeto(addobjeto));
                }
                for (String removeobjeto : removeobjetos) {
                    objactuales.get(0).remove(removeobjeto);
                    objactuales.get(1).remove(new Database().buscaNomObjeto(removeobjeto));
                }
            } else {
                ArrayList<String> objetos = new ArrayList<>();
                ArrayList<String> nomobjetos = new ArrayList<>();
                for (String variosobjeto : variosobjetos) {
                    objetos.add(variosobjeto);
                    nomobjetos.add(new Database().buscaNomObjeto(variosobjeto));
                }
                objactuales.add(objetos);
                objactuales.add(nomobjetos);
            }

            new DadsLastWeek().setListaobjetos(objactuales);
        }
        
    }
    
    private void recoverData(){
        historia = h.obtenerDecision(new DadsLastWeek().getDecision_iddecision());
        initHistory();
        isthereagamesaved = false;
    }
    
    private void pjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjbuttonActionPerformed
        new Personaje(this).setVisible(true);
    }//GEN-LAST:event_pjbuttonActionPerformed

    private void pjbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjbuttonMouseEntered
        pjbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 102), new java.awt.Color(255, 102, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_pjbuttonMouseEntered

    private void pjbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjbuttonMouseExited
        pjbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_pjbuttonMouseExited

    private void pjbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjbuttonMousePressed
        pjbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_pjbuttonMousePressed

    private void pjbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjbuttonMouseReleased
        pjbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 102), new java.awt.Color(255, 102, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_pjbuttonMouseReleased

    private void continuebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuebuttonActionPerformed
        if(!isfinal){
            historia = historia.left;
            new DadsLastWeek().setDia_coddia(historia.day);
            new DadsLastWeek().setDecision_iddecision(historia.decision);
            initHistory();
        }else{
            new Database().insertarEstadistica(new DadsLastWeek().getIdusuario(), new DadsLastWeek().getNompersonaje(), new DadsLastWeek().getApellpersonaje(), new DadsLastWeek().getSalud(), new DadsLastWeek().getEstadosalud(), new DadsLastWeek().getDecision_iddecision());
            new Estadisticas().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_continuebuttonActionPerformed

    private void optionabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionabuttonActionPerformed
        historia = historia.left;
        new DadsLastWeek().setDia_coddia(historia.day);
        new DadsLastWeek().setDecision_iddecision(historia.decision);
        s = 30;
        initHistory();
    }//GEN-LAST:event_optionabuttonActionPerformed

    private void optionbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionbbuttonActionPerformed
        historia = historia.right;
        new DadsLastWeek().setDia_coddia(historia.day);
        new DadsLastWeek().setDecision_iddecision(historia.decision);
        s = 30;
        initHistory();
    }//GEN-LAST:event_optionbbuttonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dialog = new DLWOptionPane(this, "¿Seguro que deseas regresar al menú principal?.", "Regresar","question",260,150,true);
        dialog.setVisible(true);
        if(dialog.hasAccepted()){
            new DadsLastWeek().setIsPlaying(false);
            this.dispose();
            new Menu().setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

//    private void centrarVentana() {
//        //este metodo devuelve el tamaño de la pantalla
//        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
//        //obtenemos el tamaño de la ventana
//        Dimension ventana = this.getSize();
//        //para centrar la ventana lo hacemos con el siguiente calculo
//        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
//    }    
    
    /**
     * @param args the command line arguments
     */

    //Botones
  
    Image continuarboton1 = new ImageIcon(getClass().getResource("/images/Continuar 1.png")).getImage().getScaledInstance(150, 80, Image.SCALE_AREA_AVERAGING);
    Image continuarboton2 = new ImageIcon(getClass().getResource("/images/Continuar 2.png")).getImage().getScaledInstance(150, 80, Image.SCALE_AREA_AVERAGING);
    Image continuarboton3 = new ImageIcon(getClass().getResource("/images/Continuar 3.png")).getImage().getScaledInstance(150, 80, Image.SCALE_AREA_AVERAGING);
    
    Image finalboton1 = new ImageIcon(getClass().getResource("/images/Fin 1.png")).getImage().getScaledInstance(150, 80, Image.SCALE_AREA_AVERAGING);
    Image finalboton2 = new ImageIcon(getClass().getResource("/images/Fin 2.png")).getImage().getScaledInstance(150, 80, Image.SCALE_AREA_AVERAGING);
    Image finalboton3 = new ImageIcon(getClass().getResource("/images/Fin 3.png")).getImage().getScaledInstance(150, 80, Image.SCALE_AREA_AVERAGING);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonspanel;
    private javax.swing.JLabel clockicon;
    private javax.swing.JPanel clockpanel;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton continuebutton;
    private javax.swing.JPanel continueoptionpanel;
    private javax.swing.JLabel days;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPaneFond;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton optionabutton;
    private javax.swing.JButton optionbbutton;
    private javax.swing.JButton pjbutton;
    private javax.swing.JTextPane text;
    private javax.swing.JTextArea textfond;
    private javax.swing.JLabel time;
    private javax.swing.JPanel titlepanel;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel twooptionspanel;
    // End of variables declaration//GEN-END:variables

}
