/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadlastweek;

import interfacethings.DLWOptionPane;
import interfacethings.ImageFond;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author AULA3
 */
public class Menu extends javax.swing.JFrame {
    private Cursor cursor;
    DLWOptionPane dialog;
    /**
     * Creates new form Interfaz
     */
    public Menu() {
        initComponents();        
        anotherInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pjbutton = new javax.swing.JButton();
        ImageFond image = new ImageFond();
        image.setImage("/images/Fondo.jpg");
        setContentPane(image);
        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelbuttons = new javax.swing.JPanel();
        startbutton = new javax.swing.JButton();
        continuebutton = new javax.swing.JButton();
        statsbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        charbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        account = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        pjbutton.setText("   ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menú principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        fondo.setOpaque(false);
        fondo.setLayout(new java.awt.BorderLayout());

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.add(titulo, java.awt.BorderLayout.CENTER);

        contenido.setOpaque(false);
        contenido.setLayout(new javax.swing.BoxLayout(contenido, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("                                        ");
        contenido.add(jLabel1);

        panelbuttons.setOpaque(false);
        panelbuttons.setLayout(new java.awt.GridLayout(5, 0));

        startbutton.setBorderPainted(false);
        startbutton.setContentAreaFilled(false);
        startbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttonActionPerformed(evt);
            }
        });
        panelbuttons.add(startbutton);

        continuebutton.setBorderPainted(false);
        continuebutton.setContentAreaFilled(false);
        continuebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuebuttonActionPerformed(evt);
            }
        });
        panelbuttons.add(continuebutton);

        statsbutton.setBorderPainted(false);
        statsbutton.setContentAreaFilled(false);
        statsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsbuttonActionPerformed(evt);
            }
        });
        panelbuttons.add(statsbutton);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText(" ");
        jPanel2.add(jLabel4);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        charbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        charbutton.setContentAreaFilled(false);
        charbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                charbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                charbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                charbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                charbuttonMouseReleased(evt);
            }
        });
        charbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charbuttonActionPerformed(evt);
            }
        });
        jPanel4.add(charbutton);

        jPanel2.add(jPanel4);

        jLabel3.setText(" ");
        jPanel2.add(jLabel3);

        jPanel1.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        account.setBorderPainted(false);
        account.setContentAreaFilled(false);
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });
        jPanel3.add(account);

        jPanel1.add(jPanel3);

        panelbuttons.add(jPanel1);

        contenido.add(panelbuttons);

        jLabel2.setText("                                        ");
        contenido.add(jLabel2);

        fondo.add(contenido, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anotherInitComponents(){
        
        //CURSOR
        ImageIcon imagencursor = new ImageIcon(getClass().getResource("/images/cursor.png"));
        Toolkit TK = Toolkit.getDefaultToolkit(); 
        this.cursor = TK.createCustomCursor(imagencursor.getImage(), new Point(2,2),"Cursor 01"); 
        this.setCursor(cursor);
        
        Image mini = new ImageIcon(getClass().getResource("/images/Titulo.png")).getImage().getScaledInstance(200, 95, Image.SCALE_AREA_AVERAGING);
        titulo.setIcon(new ImageIcon(mini));        
        this.setSize(410,600);
        Image ico = new ImageIcon(getClass().getResource("/images/calendar_5-512.png")).getImage().getScaledInstance(2000, 1900, Image.SCALE_AREA_AVERAGING);
        this.setIconImage(ico);
        Image personajeboton;
        
        Image empezarboton = new ImageIcon(getClass().getResource("/images/startbutton.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image continuarboton = new ImageIcon(getClass().getResource("/images/continuebutton.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image estadisticasboton = new ImageIcon(getClass().getResource("/images/statsbutton.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image cuenta = new ImageIcon(getClass().getResource("/images/account.png")).getImage().getScaledInstance(50, 50, Image.SCALE_AREA_AVERAGING);
        Image empezarbotonenfocado = new ImageIcon(getClass().getResource("/images/startbuttonfocused.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image continuarbotonenfocado = new ImageIcon(getClass().getResource("/images/continuebuttonfocused.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image estadisticasbotonenfocado = new ImageIcon(getClass().getResource("/images/statsbuttonfocused.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image cuentaenfocado = new ImageIcon(getClass().getResource("/images/exitsession.png")).getImage().getScaledInstance(50, 50, Image.SCALE_AREA_AVERAGING);
        Image empezarbotonpresionado = new ImageIcon(getClass().getResource("/images/startbuttonpressed.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image continuarbotonpresionado = new ImageIcon(getClass().getResource("/images/continuebuttonpressed.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image empezarbotondeshabilitado = new ImageIcon(getClass().getResource("/images/startbuttondisabled.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image continuarbotondeshabilitado = new ImageIcon(getClass().getResource("/images/continuebuttondisabled.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image estadisticasbotonpresionado = new ImageIcon(getClass().getResource("/images/statsbuttonpressed.png")).getImage().getScaledInstance(170, 80, Image.SCALE_AREA_AVERAGING);
        Image cuentapresionado = new ImageIcon(getClass().getResource("/images/exitsessionpressed.png")).getImage().getScaledInstance(50, 50, Image.SCALE_AREA_AVERAGING);
        if("D000".equals(new DadsLastWeek().getDia_coddia())){
            startbutton.setEnabled(false);
            startbutton.setDisabledIcon(new ImageIcon(empezarbotondeshabilitado));
        }
        if("A001".equals(new DadsLastWeek().getDecision_iddecision()) || "A000".equals(new DadsLastWeek().getDecision_iddecision())){
            continuebutton.setEnabled(false);
            continuebutton.setDisabledIcon(new ImageIcon(continuarbotondeshabilitado));
        }
        if("A000".equals(new DadsLastWeek().getDecision_iddecision())){
            personajeboton = new ImageIcon(getClass().getResource("/images/withoutphoto.png")).getImage().getScaledInstance(50,50, Image.SCALE_AREA_AVERAGING);
        }else{
            personajeboton = new Database().consultarImagen(new DadsLastWeek().getIdusuario()).getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_AREA_AVERAGING);
        }
        startbutton.setIcon(new ImageIcon(empezarboton));
        continuebutton.setIcon(new ImageIcon(continuarboton));
        statsbutton.setIcon(new ImageIcon(estadisticasboton));
        charbutton.setIcon(new ImageIcon(personajeboton));
        account.setIcon(new ImageIcon(cuenta));
        startbutton.setRolloverIcon(new ImageIcon(empezarbotonenfocado));
        continuebutton.setRolloverIcon(new ImageIcon(continuarbotonenfocado));
        statsbutton.setRolloverIcon(new ImageIcon(estadisticasbotonenfocado));
        account.setRolloverIcon(new ImageIcon(cuentaenfocado));
        startbutton.setPressedIcon(new ImageIcon(empezarbotonpresionado));
        continuebutton.setPressedIcon(new ImageIcon(continuarbotonpresionado));
        statsbutton.setPressedIcon(new ImageIcon(estadisticasbotonpresionado));
        account.setPressedIcon(new ImageIcon(cuentapresionado));
    }
    
    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountActionPerformed

    private void charbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_charbuttonMouseEntered
        charbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 102), new java.awt.Color(255, 102, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_charbuttonMouseEntered

    private void charbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_charbuttonMouseExited
        charbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_charbuttonMouseExited

    private void charbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charbuttonActionPerformed
//        this.dispose();
        new Personaje(this).setVisible(true);        
    }//GEN-LAST:event_charbuttonActionPerformed

    private void charbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_charbuttonMousePressed
        charbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_charbuttonMousePressed

    private void charbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_charbuttonMouseReleased
        charbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 102), new java.awt.Color(255, 102, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
    }//GEN-LAST:event_charbuttonMouseReleased

    private void startbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttonActionPerformed
        if (!"A001".equals(new DadsLastWeek().getDecision_iddecision()) && !"A000".equals(new DadsLastWeek().getDecision_iddecision())) {
            dialog = new DLWOptionPane(this, "Estás a punto de empezar una partida nueva. Esto borrará todos los progresos actuales.<br>¿Seguro quieres empezar una nueva partida?.", "¿Empezar de cero?","question",480,150,true);
            dialog.setVisible(true);
            
//            int option = JOptionPane.showConfirmDialog(null, "Estás a punto de empezar una partida nueva. Esto borrará todos los progresos actuales.\n¿Seguro quieres empezar una nueva partida?.", "¿Empezar de cero?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (dialog.hasAccepted()) {
                new Database().actualizarDiaYDecision(new DadsLastWeek().getIdusuario(), "D001", "A001");
                new Database().borrarTodosLosObjetos(new DadsLastWeek().getIdusuario());
                new Database().actualizarPersonaje(new DadsLastWeek().getIdusuario(), new DadsLastWeek().getNompersonaje(), new DadsLastWeek().getApellpersonaje(), 100, "Normal");
                new DadsLastWeek().setDia_coddia("D001");
                new DadsLastWeek().setDecision_iddecision("A001");
                new DadsLastWeek().setListaobjetos(new ArrayList<>());
                new DadsLastWeek().setSalud(100);
                new DadsLastWeek().setEstadosalud("Normal");
                boolean isthereagamesaved = false;
                new Game(isthereagamesaved).setVisible(true);
                this.setVisible(false);
            }
        }else{
            new Database().actualizarDiaYDecision(new DadsLastWeek().getIdusuario(), "D001", "A001");
            new DadsLastWeek().setDia_coddia("D001");
            new DadsLastWeek().setDecision_iddecision("A001");
            new DadsLastWeek().setListaobjetos(new ArrayList<>());
            new DadsLastWeek().setSalud(100);
            new DadsLastWeek().setEstadosalud("Normal");
            boolean isthereagamesaved = false;
            new Game(isthereagamesaved).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_startbuttonActionPerformed

    private void continuebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuebuttonActionPerformed
        boolean isthereagamesaved = true;
        new Game(isthereagamesaved).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_continuebuttonActionPerformed

    private void statsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsbuttonActionPerformed
        new Estadisticas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_statsbuttonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dialog = new DLWOptionPane(this, "¿Seguro que deseas salir del juego?.", "Salir","question",260,150,true);
        dialog.setVisible(true);
        if(dialog.hasAccepted()){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(!"D000".equals(new DadsLastWeek().getDia_coddia())){
            startbutton.setEnabled(true);
        }
        if(!"A001".equals(new DadsLastWeek().getDecision_iddecision()) && !"A000".equals(new DadsLastWeek().getDecision_iddecision())){
            continuebutton.setEnabled(true);
        }
        
        Image personajeboton;
        if("A000".equals(new DadsLastWeek().getDecision_iddecision())){
            personajeboton = new ImageIcon(getClass().getResource("/images/withoutphoto.png")).getImage().getScaledInstance(50,50, Image.SCALE_AREA_AVERAGING);
        }else{
            personajeboton = new Database().consultarImagen(new DadsLastWeek().getIdusuario()).getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_AREA_AVERAGING);
        }
        charbutton.setIcon(new ImageIcon(personajeboton));
    }//GEN-LAST:event_formWindowActivated
    
//    private void centrarVentana() {
//        //este metodo devuelve el tamaño de la pantalla
//        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
//        //obtenemos el tamaño de la ventana
//        Dimension ventana = this.getSize();
//        //para centrar la ventana lo hacemos con el siguiente calculo
//        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
//    }
    
    /**
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account;
    private javax.swing.JButton charbutton;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton continuebutton;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelbuttons;
    private javax.swing.JButton pjbutton;
    private javax.swing.JButton startbutton;
    private javax.swing.JButton statsbutton;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
