/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dadlastweek;

import interfacethings.DLWOptionPane;
import interfacethings.ImageFond;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AULA3
 */

public class Personaje extends javax.swing.JDialog{
    DLWOptionPane dialog;
    DefaultListModel listaobjetos = new DefaultListModel();
    FileInputStream fis;
    int longitudBytes;
    boolean isFileUpdated = false;
    private Cursor cursor;
    
    JFileChooser archivos = new JFileChooser();
    FileNameExtensionFilter filterjpg = new FileNameExtensionFilter("Archivos de imagen (.jpg)", "jpg");
    FileNameExtensionFilter filterpng = new FileNameExtensionFilter("Archivos de imagen (.png)", "png");
    FileNameExtensionFilter filterbmp = new FileNameExtensionFilter("Archivos de imagen (.bmp)", "bmp");
    FileNameExtensionFilter filtergif = new FileNameExtensionFilter("Archivos de imagen (.gif)", "gif");
    FileNameExtensionFilter filtertif = new FileNameExtensionFilter("Archivos de imagen (.tif)", "tif");
    /**
     * Creates new form Interfaz
     * @param parent
     */
    
    public Personaje(javax.swing.JFrame parent) {
        super(parent, true);
        initComponents();
        anotherInitComponents();
    }
    
    public Personaje() {
        initComponents(); 
        anotherInitComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageFond image = new ImageFond();
        image.setImage("/images/Fondo.jpg");
        setContentPane(image);
        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lockedpanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        locked = new javax.swing.JLabel();
        pjimgpanel = new javax.swing.JPanel();
        pjimagebutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labelpjname = new javax.swing.JLabel();
        nombrepj = new javax.swing.JTextField();
        labelpjlastname = new javax.swing.JLabel();
        apellidopj = new javax.swing.JTextField();
        statehealth = new javax.swing.JPanel();
        labelpjhealthstate = new javax.swing.JLabel();
        pjsaludestado = new javax.swing.JLabel();
        healthpercent = new javax.swing.JPanel();
        labelpjhealthperc = new javax.swing.JLabel();
        pjsaludporc = new javax.swing.JLabel();
        labelporcentaje = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        minifondpanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        inventario = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pjcreationbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear personaje");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        fondo.setOpaque(false);
        fondo.setLayout(new java.awt.BorderLayout());

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.add(titulo, java.awt.BorderLayout.CENTER);

        contenido.setOpaque(false);
        contenido.setLayout(new javax.swing.BoxLayout(contenido, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText(" ");
        jPanel1.add(jLabel2);

        jPanel4.add(jPanel1);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("            ");
        jPanel7.add(jLabel4);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));

        lockedpanel.setOpaque(false);
        lockedpanel.setLayout(new java.awt.BorderLayout());

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setText(" ");
        jPanel13.add(jLabel7);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        jLabel11.setText(" ");
        jPanel14.add(jLabel11);

        locked.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel14.add(locked);

        jPanel13.add(jPanel14);

        lockedpanel.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel8.add(lockedpanel);

        pjimgpanel.setOpaque(false);
        pjimgpanel.setLayout(new java.awt.GridLayout(1, 0));

        pjimagebutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        pjimagebutton.setContentAreaFilled(false);
        pjimagebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pjimagebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pjimagebuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pjimagebuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pjimagebuttonMouseReleased(evt);
            }
        });
        pjimagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjimagebuttonActionPerformed(evt);
            }
        });
        pjimgpanel.add(pjimagebutton);

        jPanel8.add(pjimgpanel);

        jPanel7.add(jPanel8);

        jLabel3.setText("            ");
        jPanel7.add(jLabel3);

        jPanel4.add(jPanel7);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText(" ");
        jPanel6.add(jLabel1);

        jPanel4.add(jPanel6);

        jPanel2.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("     ");
        jPanel5.add(jLabel5);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(6, 0));

        labelpjname.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        labelpjname.setText("Nombre: ");
        jPanel9.add(labelpjname);

        nombrepj.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        nombrepj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0, 32), new java.awt.Color(0, 0, 0, 32), new java.awt.Color(0, 0, 0, 96), new java.awt.Color(0, 0, 0, 96)));
        nombrepj.setOpaque(false);
        nombrepj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrepjKeyTyped(evt);
            }
        });
        jPanel9.add(nombrepj);

        labelpjlastname.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        labelpjlastname.setText("Apellido: ");
        jPanel9.add(labelpjlastname);

        apellidopj.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        apellidopj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0, 32), new java.awt.Color(0, 0, 0, 32), new java.awt.Color(0, 0, 0, 96), new java.awt.Color(0, 0, 0, 96)));
        apellidopj.setOpaque(false);
        apellidopj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidopjKeyTyped(evt);
            }
        });
        jPanel9.add(apellidopj);

        statehealth.setOpaque(false);
        statehealth.setLayout(new javax.swing.BoxLayout(statehealth, javax.swing.BoxLayout.LINE_AXIS));

        labelpjhealthstate.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        labelpjhealthstate.setText("Estado: ");
        statehealth.add(labelpjhealthstate);

        pjsaludestado.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        pjsaludestado.setText("Normal");
        statehealth.add(pjsaludestado);

        jPanel9.add(statehealth);

        healthpercent.setOpaque(false);
        healthpercent.setLayout(new javax.swing.BoxLayout(healthpercent, javax.swing.BoxLayout.LINE_AXIS));

        labelpjhealthperc.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        labelpjhealthperc.setText("Salud: ");
        healthpercent.add(labelpjhealthperc);

        pjsaludporc.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        pjsaludporc.setForeground(new java.awt.Color(255, 0, 0));
        pjsaludporc.setText("100");
        healthpercent.add(pjsaludporc);

        labelporcentaje.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        labelporcentaje.setForeground(new java.awt.Color(255, 0, 0));
        labelporcentaje.setText("%");
        healthpercent.add(labelporcentaje);

        jPanel9.add(healthpercent);

        jPanel5.add(jPanel9);

        jLabel6.setText("           ");
        jPanel5.add(jLabel6);

        jPanel2.add(jPanel5);

        jPanel11.add(jPanel2);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        jLabel10.setText("       ");
        jPanel12.add(jLabel10);

        minifondpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        minifondpanel.setOpaque(false);
        minifondpanel.setLayout(new java.awt.BorderLayout());

        jScrollPane.setBorder(null);
        jScrollPane.setOpaque(false);

        inventario.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        inventario.setOpaque(false);
        jScrollPane.setViewportView(inventario);

        minifondpanel.add(jScrollPane, java.awt.BorderLayout.CENTER);

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INVENTARIO");
        minifondpanel.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jPanel12.add(minifondpanel);

        jLabel9.setText("       ");
        jPanel12.add(jLabel9);

        jPanel11.add(jPanel12);

        contenido.add(jPanel11);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        pjcreationbutton.setBorderPainted(false);
        pjcreationbutton.setContentAreaFilled(false);
        pjcreationbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pjcreationbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(pjcreationbutton);

        closebutton.setBorderPainted(false);
        closebutton.setContentAreaFilled(false);
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        jPanel3.add(closebutton);

        contenido.add(jPanel3);

        fondo.add(contenido, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anotherInitComponents(){

        //CURSOR
        ImageIcon imagencursor = new ImageIcon(getClass().getResource("/images/cursor.png"));
        Toolkit TK = Toolkit.getDefaultToolkit(); 
        this.cursor = TK.createCustomCursor(imagencursor.getImage(), new Point(2,2),"Cursor 01"); 
        this.setCursor(cursor);
        
        new DadsLastWeek().setIsPjWindowOpened(true);
        jScrollPane.getViewport().setOpaque(false);
        minifondpanel.setBackground(new Color(0, 0, 0, 64));
        inventario.setBorder(null);
        inventario.setBackground(new Color(0, 0, 0, 96));
        nombrepj.setBackground(new Color(0, 0, 0, 64));
        apellidopj.setBackground(new Color(0, 0, 0, 64));
//        inventario.setForeground(new Color(0, 0, 0, 64));
        inventario.setSelectionBackground(new Color(0, 0, 0, 128));
        Image personajeboton;
        nombrepj.setText(new DadsLastWeek().getNompersonaje());
        apellidopj.setText(new DadsLastWeek().getApellpersonaje());
        pjsaludporc.setText(String.valueOf(new DadsLastWeek().getSalud()));
        pjsaludestado.setText(new DadsLastWeek().getEstadosalud());
               
               
        Image mini = new ImageIcon(getClass().getResource("/images/Titulo.png")).getImage().getScaledInstance(200, 95, Image.SCALE_AREA_AVERAGING);
        titulo.setIcon(new ImageIcon(mini));        
        this.setSize(400,610);
        Image ico = new ImageIcon(getClass().getResource("/images/calendar_5-512.png")).getImage().getScaledInstance(2000, 1900, Image.SCALE_AREA_AVERAGING);
        this.setIconImage(ico);
        Image crearpjboton = new ImageIcon(getClass().getResource("/images/createpjbutton.png")).getImage().getScaledInstance(140, 60, Image.SCALE_AREA_AVERAGING);
        Image cerrarboton = new ImageIcon(getClass().getResource("/images/closebutton.png")).getImage().getScaledInstance(140, 60, Image.SCALE_AREA_AVERAGING);
        Image crearpjbotonenfocado = new ImageIcon(getClass().getResource("/images/createpjbuttonfocused.png")).getImage().getScaledInstance(140, 60, Image.SCALE_AREA_AVERAGING);
        Image cerrarbotonenfocado = new ImageIcon(getClass().getResource("/images/closebuttonfocused.png")).getImage().getScaledInstance(140, 60, Image.SCALE_AREA_AVERAGING);
        Image crearpjbotonpresionado = new ImageIcon(getClass().getResource("/images/createpjbuttonpressed.png")).getImage().getScaledInstance(140, 60, Image.SCALE_AREA_AVERAGING);
        Image cerrarbotonpresionado = new ImageIcon(getClass().getResource("/images/closebuttonpressed.png")).getImage().getScaledInstance(140, 60, Image.SCALE_AREA_AVERAGING);
        Image crearpjbotondeshabilitado = new ImageIcon(getClass().getResource("/images/createpjbuttondisabled.png")).getImage().getScaledInstance(140, 60, Image.SCALE_AREA_AVERAGING);
        Image candado = new ImageIcon(getClass().getResource("/images/Lockedicon.png")).getImage().getScaledInstance(25, 25, Image.SCALE_AREA_AVERAGING);
        pjcreationbutton.setIcon(new ImageIcon(crearpjboton));
        closebutton.setIcon(new ImageIcon(cerrarboton));
        pjcreationbutton.setRolloverIcon(new ImageIcon(crearpjbotonenfocado));
        closebutton.setRolloverIcon(new ImageIcon(cerrarbotonenfocado));
        pjcreationbutton.setPressedIcon(new ImageIcon(crearpjbotonpresionado));
        closebutton.setPressedIcon(new ImageIcon(cerrarbotonpresionado));
        pjcreationbutton.setDisabledIcon(new ImageIcon(crearpjbotondeshabilitado));
        locked.setIcon(new ImageIcon(candado));
        if("A000".equals(new DadsLastWeek().getDecision_iddecision())){
            personajeboton = new ImageIcon(getClass().getResource("/images/withoutphoto.png")).getImage().getScaledInstance(150,150, Image.SCALE_AREA_AVERAGING);
        }else{
            personajeboton = new Database().consultarImagen(new DadsLastWeek().getIdusuario()).getImage().getScaledInstance(150, 150, java.awt.Image.SCALE_AREA_AVERAGING);
        }
        if(!"D000".equals(new DadsLastWeek().getDia_coddia())){
            pjimagebutton.setEnabled(false);
            pjimagebutton.setDisabledIcon(new ImageIcon(personajeboton));
            pjcreationbutton.setEnabled(false);
            nombrepj.setEnabled(false);
            apellidopj.setEnabled(false);
        }else{
            lockedpanel.setVisible(false);            
        }
        pjimagebutton.setIcon(new ImageIcon(personajeboton));
        
        ArrayList<ArrayList<String>> objetos = new DadsLastWeek().getListaobjetos();
        
        if(!objetos.isEmpty()){
            for(int i = 0; i < objetos.get(1).size(); i++){
                listaobjetos.addElement(objetos.get(1).get(i));
            }
            inventario.setModel(listaobjetos);
        }else{
            inventario.removeAll();
        }      
    }
    
    private void nombrepjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrepjKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || nombrepj.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_nombrepjKeyTyped

    private void apellidopjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidopjKeyTyped
        if (Character.isDigit(evt.getKeyChar()) || apellidopj.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_apellidopjKeyTyped

    private void pjcreationbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjcreationbuttonActionPerformed
        new Database().actualizarPersonaje(new DadsLastWeek().getIdusuario(), nombrepj.getText(), apellidopj.getText(), Integer.parseInt(pjsaludporc.getText()), pjsaludestado.getText());
        if (isFileUpdated) {
            new Database().subirImagen(fis, longitudBytes, new DadsLastWeek().getIdusuario());            
        }
        new Database().actualizarDiaYDecision(new DadsLastWeek().getIdusuario(), "D001", "A001");
        new DadsLastWeek().setDia_coddia("D001");
        new DadsLastWeek().setDecision_iddecision("A001");
        new DadsLastWeek().setNompersonaje(nombrepj.getText());
        new DadsLastWeek().setApellpersonaje(apellidopj.getText());
        new DadsLastWeek().setSalud(Integer.parseInt(pjsaludporc.getText()));
        new DadsLastWeek().setEstadosalud(pjsaludestado.getText());
        dialog = new DLWOptionPane(this, "La creación del personaje ha sido exitosa.", "Personaje creado","info",300,150,false);
        dialog.setVisible(true);
//        JOptionPane.showMessageDialog(null, "La creación de personaje ha sido exitosa.", "Personaje creado", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
//        new Menu().setVisible(true);
    }//GEN-LAST:event_pjcreationbuttonActionPerformed

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        this.dispose();
        new DadsLastWeek().setIsPjWindowOpened(false);
//        if(!new DadsLastWeek().isIsPlaying()){
//            new Menu().setVisible(true);
//        }
    }//GEN-LAST:event_closebuttonActionPerformed

    private void pjimagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pjimagebuttonActionPerformed
        archivos.setFileFilter(filterbmp);
        archivos.setFileFilter(filtertif);
        archivos.setFileFilter(filtergif);
        archivos.setFileFilter(filterjpg);
        archivos.setFileFilter(filterpng);   
        
        archivos.setFileSelectionMode(JFileChooser.FILES_ONLY);//solo archivos y no carpetas
        JLabel preview = new JLabel();
        preview.setPreferredSize(new Dimension(200, 200));
        preview.setHorizontalAlignment(JLabel.CENTER);
        preview.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        archivos.setAccessory(preview);
        archivos.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
            try {
                if (evt1.getPropertyName().equals(JFileChooser.SELECTED_FILE_CHANGED_PROPERTY)) {
                    preview.setText("");
                    preview.setIcon(new ImageIcon(new ImageIcon(archivos.getSelectedFile().getPath()).getImage().getScaledInstance(200, 200, Image.SCALE_AREA_AVERAGING)));
                }
            }catch(NullPointerException ex){
                preview.setText("El archivo no puede visualizarse");
            }
        });
        int seleccion = archivos.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                fis = new FileInputStream(archivos.getSelectedFile());
                //necesitamos saber la cantidad de bytes
                longitudBytes = (int) archivos.getSelectedFile().length();
                try {
                    Image icono = ImageIO.read(archivos.getSelectedFile()).getScaledInstance(150, 150, Image.SCALE_DEFAULT);
                    pjimagebutton.setIcon(new ImageIcon(icono));
                    isFileUpdated = true;
//                    pjimagebutton.updateUI();
                } catch (IOException | NullPointerException ex) {
                    dialog = new DLWOptionPane(this, "El archivo no pudo abrirse correctamente.", "Advertencia","error",300,150,false);
                    dialog.setVisible(true);
//                    JOptionPane.showMessageDialog(null, "El archivo no pudo abrirse correctamente.", "Advertencia", JOptionPane.ERROR_MESSAGE);
                }
            } catch (FileNotFoundException ex) {
                dialog = new DLWOptionPane(this, "El archivo no pudo abrirse correctamente.", "Advertencia","error",300,150,false);
                dialog.setVisible(true);
//                JOptionPane.showMessageDialog(null, "El archivo no pudo abrirse correctamente.", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_pjimagebuttonActionPerformed

    private void pjimagebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjimagebuttonMouseEntered
        if("D000".equals(new DadsLastWeek().getDia_coddia())){
            pjimagebutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 102), new java.awt.Color(255, 102, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        }
    }//GEN-LAST:event_pjimagebuttonMouseEntered

    private void pjimagebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjimagebuttonMouseExited
        if("D000".equals(new DadsLastWeek().getDia_coddia())){
            pjimagebutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        }
    }//GEN-LAST:event_pjimagebuttonMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new DadsLastWeek().setIsPjWindowOpened(false);
//        if(!new DadsLastWeek().isIsPlaying()){
//            new Menu().setVisible(true);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void pjimagebuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjimagebuttonMousePressed
        if("D000".equals(new DadsLastWeek().getDia_coddia())){
            pjimagebutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2)));
        }
    }//GEN-LAST:event_pjimagebuttonMousePressed

    private void pjimagebuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pjimagebuttonMouseReleased
        if("D000".equals(new DadsLastWeek().getDia_coddia())){
            pjimagebutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 102), new java.awt.Color(255, 102, 51)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        }
    }//GEN-LAST:event_pjimagebuttonMouseReleased

//    private void centrarVentana() {
//        //este metodo devuelve el tamaño de la pantalla
//        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
//        //obtenemos el tamaño de la ventana
//        Dimension ventana = this.getSize();
//        //para centrar la ventana lo hacemos con el siguiente calculo
//        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
//    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidopj;
    private javax.swing.JButton closebutton;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel healthpercent;
    private javax.swing.JList<String> inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelpjhealthperc;
    private javax.swing.JLabel labelpjhealthstate;
    private javax.swing.JLabel labelpjlastname;
    private javax.swing.JLabel labelpjname;
    private javax.swing.JLabel labelporcentaje;
    private javax.swing.JLabel locked;
    private javax.swing.JPanel lockedpanel;
    private javax.swing.JPanel minifondpanel;
    private javax.swing.JTextField nombrepj;
    private javax.swing.JButton pjcreationbutton;
    private javax.swing.JButton pjimagebutton;
    private javax.swing.JPanel pjimgpanel;
    private javax.swing.JLabel pjsaludestado;
    private javax.swing.JLabel pjsaludporc;
    private javax.swing.JPanel statehealth;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

}
